web:
  build: .
  environment:
    MYENV: EXAMPLE
  volumes:
    - .:/code
web_migrations:
  extends:
    service: web
  command: python manage.py makemigrations credit_e_weather   
web_migrate:
  extends:
    service: web
  command: python manage.py migrate credit_e_weather
web_run:
  extends:
    service: web
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"